// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LayoutHeaderBodyFooter: typeof import('./src/components/layout/HeaderBodyFooter.vue')['default']
    LayoutHeaderMainFooter: typeof import('./src/components/layout/HeaderMainFooter.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    Logout: typeof import('./src/components/Logout/Logout.vue')['default']
    Register: typeof import('./src/components/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
